name: Cron Test

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '02 17 * * *'

jobs:
  call-shared-workflow-1:
    uses: MartinJuneie/temp/.github/workflows/shared_wf.yml@main
    with:
      branch_name: 'main'

  call-shared-workflow-2:
    needs: call-shared-workflow-1
    uses: MartinJuneie/temp/.github/workflows/shared_wf.yml@main
    with:
      branch_name: 'testbranch'