name: Cron Test

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '02 17 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Say hello from branch
        run: |
          TIMESTAMP=$(date -u + "%Y-%m-%d %H:%M:%S.%f %Z")
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Hello from $BRANCH_NAME on $TIMESTAMP"

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: testbranch

      - name: Say hello from branch
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "Hello from $BRANCH_NAME"
          cat testfile.txt
