name: Cron Test

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '02 17 * * *'

jobs:
  call-shared-on-branches:
    strategy:
      matrix:
        branch: [main, testbranch]
    uses: MartinJuneie/temp/.github/workflows/shared_wf.yml@main
    with:
      branch: ${{ matrix.branch }}
    secrets: inherit