name: Cron Test

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '02 17 * * *'

jobs:
  call-shared-on-branches:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, testbranch]
    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

        - name: call-shared-workflow-2:
          uses: MartinJuneie/temp/.github/workflows/shared_wf.yml@main